#!/usr/bin/python3
# -*- coding: utf-8 -*-

import logging
import re

class PersonList:
    content = [
        [
            "Abele von und zu Lilienberg, Matthias", 
            "118500147", 
            "1", 
            "Matthias Abele von und zu Lilienberg", 
            "lilienberg", 
            "(matthias abele|zu lilienberg)", 
            "1618", 
            "1618", 
            "",
			"1677", 
            "1677", 
            "", 
            "Mann", 
            "Österreichischer Jurist und Schriftsteller"
        ],
        [
			"Abraham à Sancta Clara",
			"11850021X",
			"1",
			"Abraham, a Sancta Clara",
			"sancta clara",
			"(abraham a|sancta clara)",
			"2. Juli 1644",
			"1644",
			"Kreenheinstetten",
			"1. Dezember 1709",
			"1709",
			"Wien",
			"Mann",
			"Österreichischer katholischer Theologe, Literat und Prediger; Augustiner-Barfüßer (OAD); galt als bekannter Kanzelredner und Satiriker"
		],
        [
			"Abschatz, Hans Aßmann Freiherr von",
			"118500279",
			"1",
			"Hans Assmann von Abschatz",
			"abschatz",
			"(hans assmann|von abschatz)",
			"4. Februar 1646",
			"1646",
			"Würbitz",
			"22. April 1699",
			"1699",
			"Liegnitz",
			"Mann",
			"Dt. Lyriker schles. Herkunft; Dichter; Diplomat, Übersetzer ; Studium der Rechte in Straßburg und Leyden; Landesbestallter des Herzogtums Liegnitz; Übersetzer italienischer Lyrik"
		],
        [
			"Albert, Heinrich",
			"121418952",
			"1",
			"Heinrich Albert",
			"heinrich albert",
			"(heinrich|hei?nricus) alberti?",
			"28. Juni 1604",
			"1604",
			"Bad Lobenstein",
			"6. Oktober 1651",
			"1651",
			"Königsberg",
			"Mann",
			"Deutscher Komponist, Organist, Schriftsteller, Liederdichter"
		],
        [
			"Albertinus, Aegidius",
			"118501518",
			"1",
			"Aegidius Albertinus",
			"aegidius albertinus",
			"(aegidius albertinus|maeugidi)",
			"1560",
			"1560",
			"Deventer",
			"9. März 1620",
			"1620",
			"München",
			"Mann",
			"Dt.-niederländ. Übersetzer und Dichter der Gegenreformation; Hofkanzlist und später Hofbibliothekar bei Herzog Maximilian in München"
		],
        [
			"Albini, Johann Georg d. Ä.",
			"115400206",
			"1",
			"Johann Georg Albinus",
			"georg albinus",
			"johann(es)? (georg(e|ius)? )(albin(i|us)|weiße?)",
			"6. März 1624",
			"1624",
			"",
			"25. Mai 1679",
			"1679",
			"Naumburg (Saale)",
			"Mann",
			"deutscher Theologe und Pfarrer des 17. Jahrhunderts , wirkte auch als Schriftsteller"
		],
        [
			"Albini, Johann Georg d. J.",
			"115400214",
			"1",
			"Johann Georg Albinus",
			"georg albinus",
			"johann(es)? (georg(e|ius)? )(albin(i|us)|weiße?)",
			"1659",
			"1659",
			"Naumburg (Saale)",
			"1714",
			"1714",
			"",
			"Mann",
			"Student in Jena, Erfurt"
		],
        [
			"Andreae, Johann Valentin",
			"118502883",
			"1",
			"Johann Valentin Andreä",
			"valentin andre",
			"johann(es)? (valentin(us)? )?andre(ä|ae)",
			"17. August 1586",
			"1586",
			"Herrenberg",
			"27. Juni 1654",
			"1654",
			"Stuttgart",
			"Mann",
			"Rosenkreuzer ; Huldrich StarckMann und Huldrich StarkMann sind Pseud. von J.V. Andreä"
		],
        [
			"Anton Ulrich, Herzog zu Braunschweig und Lüneburg",
			"118503472",
			"1",
			"Anton Ulrich, Braunschweig-Lüneburg, Herzog",
			"anton ulrich",
			"anton(ius)? u(da)?lric(h|us)",
			"4. Oktober 1633",
			"1633",
			"Hitzacker (Elbe)",
			"27. März 1714",
			"1714",
			"Salzdahlum",
			"Mann",
			"1667 Statthalter, 1685 Mitregent seines Bruders Rudolf August von Braunschweig-Wolfenbüttel, 1704 alleiniger Regent des Herzogtums Braunschweig- Wolfenbüttel; 1709 geheimer Übertritt zum Katholizismus, 1710 öffentliche Konversion; War maßgeblich am Übertritt seiner Enkelin Elisabeth Christine von Braunschweig- Wolfenbüttel zum Katholizismus und deren Vermählung mit Karl VI. deutscher Kaiser beteiligt; Mitglied der Fruchtbringenden Gesellschaft (Der Siegprangende), Dichter von 61 Kirchenliedern, Romanautor und Verfasser von Bühnenstücken"
		],
        [
			"Arnold, Gottfried",
			"118650386",
			"1",
			"Gottfried Arnold",
			"gottfried arnold",
			"(christoph(orus)? irenaeus|gottfried arnold(i|us)?)",
			"5. September 1666",
			"1666",
			"Annaberg (Erzgebirge)",
			"30. Mai 1714",
			"1714",
			"Perleberg",
			"Mann",
			"Dt. ev. Theologe und Kirchenhistoriker; 1682 Gymnasiast in Gera; 1685 Student in Wittenberg; 1693 Hofmeister in Quedlinburg; 1697-1698 Prof. hist. in Gießen; 1702 Prediger in Allstedt; 1705 Pastor in Werben, ab 1707 in Perleberg; kgl.-preuß. Historiograph"
		],
        [
			"Augsburger, August",
			"12415347X",
			"1",
			"August Augspurger",
			"augspurger",
			"august(us)? augs[bp]urger(us)?",
			"1620",
			"1620",
			"",
			"1675",
			"1675",
			"",
			"Mann",
			"Respondent an der Univ. Leipzig; Amtsvogt; Dichter"
		],
        [
			"Avancini, Nicolaus von",
			"100019382",
			"1",
			"Niccolò Avancini",
			"avancini",
			"ni[ck]c?ol(ò|aus) avancin(i|us)",
			"1. Dezember 1611",
			"1611",
			"Brez bei Bozen",
			"6. Dezember 1686",
			"1686",
			"",
			"Mann",
			"Prof. f. Rhetorik, Philosophie (1641) u. Theologie (1646) an der Univ. Wien, ab 1664 im Ordensdienst Rektor der Kollegien in Passau, Wien u. Graz, 1675 Visitator f. Böhmen, 1676 Provinzial f. Österreich, 1682 Assistent des Ordensgenerals in Rom"
		],
        [
			"Balde, Jacob",
			"118506137",
			"1",
			"Jakob Balde",
			"ob balde",
			"[ij]a[ck]ob(us)? baldes?(ius)?",
			"4. Januar 1604",
			"1604",
			"Ensisheim",
			"9. August 1668",
			"1668",
			"Neuburg a.d. Donau",
			"Mann",
			"Dt. Jesuit; neulat. Lyriker, Hofhistoriograph"
		],
        [
			"Barth, Caspar von",
			"118657380",
			"1",
			"Caspar von Barth",
			"von barth",
			"([ck]aspar(us)? (von|a) barth?|t[ae]rraeus (h. )?(hebi?us|speriga)|c\\. ?v(ictor|\\.) vigilius|(nobilis|hebius) a speri?ga|philoxenus gon(ä|ae)us|th?arr(ae|ä)us (helius|hibius)|eusth?a(ch|t)ius s(ch)?war[tz](ius)?)",
			"21. Juni 1587",
			"1587",
			"Küstrin",
			"18. September 1658",
			"1658",
			"Leipzig",
			"Mann",
			"Dt. Humanist, (Alt)-Philologe, Philosoph, Schriftsteller, Übersetzer; 1607 in Wittenberg immatrikuliert, lebte als Privatgelehrter in Leipzig und Halle"
		],
        [
			"Beccau, Joachim",
			"142483435",
			"1",
			"Joachim Beccau",
			"beccau",
			"joachim(us)? bec[ck]au",
			"1690",
			"1690",
			"",
			"1755",
			"1755",
			"",
			"Mann",
			""
		],
        [
			"Becher, Johann Joachim",
			"118507923",
			"1",
			"Johann Joachim Becher",
			"achim becher",
			"johann(es)?( joachim(us)?)? becc?her(us)?",
            "6. Mai 1635",
			"1635",
			"Speyer",
			"XX.10.1682",
			"1682",
			"London",
			"Mann",
			"gDt. Mediziner, Chemiker und Volkswirtschaftler, Verfasser eines Sprachenschemas"
		],
        [
			"Beck, Johann Joseph",
			"102488134",
			"1",
			"Johann Joseph Beckh",
			"beckh",
			"johann[es]( joseph)? beckh?",
            "1635",
			"1635",
			"Straßburg",
			"1692",
			"1692",
			"Kiel",
			"Mann",
			"Dt. Barockdichter und Jurist, Dramatiker und Verf. geistlicher Lieder; wirkte in Dresden, Zerbst, Hamburg, Eckernförde, Kiel; laut WBIS nicht vor 1692 und wahrscheinlich in Kiel gestorben"
		],
        [
			"Beer, Johann",
			"118508253",
			"1",
			"Johann Beer",
			"johann beer",
			"",                                        "18. März 1655",
			"1655",
			"Sankt Georgen im Attergau",
			"6. August 1700",
			"1700",
			"Weißenfels",
			"Mann",
			"Dt. Dichter, Kammermusiker, Bibliothekar und Komponist; Konzertmeister in Weißenfels"
		],
        [
			"Bernegger, Matthias",
			"11614419X",
			"1",
			"Matthias Bernegger",
			"bernegger",
			"",                            "8. Februar 1582",
			"1582",
			"",
			"5. Februar 1640",
			"1640",
			"",
			"Mann",
			"Prof. an der Univ. Straßburg ; Historiker, Philologe ; Dt. Historiker, Philologe, Mathematiker; Prof. an der Univ. Strassburg ; Historiker, Philologe, Mathematiker, Prof. an der Univ. Straßburg"
		],
        [
			"Besser, Johann von",
			"11851024X",
			"1",
			"Johann von Besser",
			"von besser",
			"",                             "8. Mai 1654",
			"1654",
			"Saldus",
			"10. Februar 1729",
			"1729",
			"",
			"Mann",
			"aus Frauenburg/Kurland; Resp. in Königsberg; Berlin, Dresden (Wirkungsorte); Dt. Dichter, Hofdichter, Zeremonienmeister ; Buchbesitz: Privatbibliothek Johann von Besser"
		],
        [
			"Betke, Joachim",
			"119160242",
			"1",
			"Joachim Betke",
			"achim betke",
			"",                                    "8. Oktober 1601",
			"1601",
			"Spandau",
			"12. Dezember 1663",
			"1663",
			"Linum",
			"Mann",
			"Dt. ev.-luth. Theologe und Spiritualist; 1624 Student in Wittenberg; 1627 Konrektor in Neuruppin; 1628-1663 Pfarrer in Linum b. Fehrbellin"
		],
        [
			"Bidermann, Jacob",
			"118510665",
			"1",
			"Jakob Bidermann",
			"bidermann",
			"",                                  "XX.XX.1578",
			"1578",
			"Ehingen (Donau)",
			"20. August 1639",
			"1639",
			"Rom",
			"Mann",
			"Dt. Barockdichter; Jesuit (seit 1594); Professor in Dillingen an der Donau (1615-1626) ; Schriftsteller, Theologe"
		],
        [
			"Birken, Sigismund von",
			"118511270",
			"1",
			"Sigmund von Birken",
			"von birken",
			"",                         "25. April 1626",
			"1626",
			"Skalná",
			"12. Juni 1681",
			"1681",
			"Nürnberg",
			"Mann",
			"Dt. Barockdichter; seit 1629 in Nürnberg ansässig; ab 1645 Mitglied und 1662 Präsident des Pegnesischen Blumenordens Nürnberg (Pegnitz-Schäfer Floridan), ab 1658 der Fruchtbringenden Gesellschaft (Der Erwachsene); Student in Jena (1643 imm.); 1654 nobilitiert"
		],
        [
			"Böhme, Jacob",
			"118512579",
			"1",
			"Jakob Böhme",
			"jakob böhme",
			"",                                        "1575",
			"1575",
			"Alt-Seidenberg",
			"17. November 1624",
			"1624",
			"Görlitz",
			"Mann",
			"Schuhmachermeister in Görlitz, ab 1613 Garnhändler; später mit Schreibverbot belegt (initiiert durch Oberpfarrer Gregor Richter)"
		],
        [
			"Böhme, Martin",
			"123261368",
			"1",
			"Martin Behm",
			"martin behm",
			"",
			"16. September 1557",
			"1557",
			"Lauban",
			"5. Februar 1622",
			"1622",
			"Lauban",
			"Mann",
			"Dt. ev. Theologe, Dramatiker und Liederdichter; 1581 Diakon und 1586 Pastor in Lauban"
		],
        [
			"Bohse, August",
			"11851296X",
			"1",
			"August Bohse",
			"august bohse",
			"",
			"1661",
			"1661",
			"Halle (Saale)",
			"1740",
			"1740",
			"Liegnitz",
			"Mann",
			"Dt. Jurist, galanter Dichter u. Komponist; 1700: Promotion in Jena; ab 1708: Professor an der Ritterakademie in Liegnitz"
		],
        [
			"Breckling, Friedrich",
			"11643998X",
			"2",
			"Friedrich Breckling",
			"friedrich beckling",
			"",
			"5. Februar 1629",
			"1629",
			"Handewitt",
			"16. März 1711",
			"1711",
			"Den Haag",
			"Mann",
			"Dt. ev. Theologe; Vertreter des Spiritualismus; Studium in Königsberg (1648), Helmstedt und Jena, Wittenberg (1651), Gießen (1652, dort 1653 Magister),  Straßburg (1655) und Rostock (1656); 1657 Substitut und 1658 Pfarrer in Handewitt; 1659 Amtsenthebung wegen seiner Kritik an Staat und Kirche, 1660 Aufnahme bei Johann Amos Comenius in Amsterdam; 1661 lutherischer Pfarrer in Zwolle, 1668 Entlassung wegen scharfer Kirchenkritik; lebte 1672-1690 in Amsterdam, ab 1690 in Den Haag"
		],
        [
			"Brehme, Christian",
			"121636011",
			"2",
			"Christian Brehme",
			"christian brehme",
			"",
			"26. April 1613",
			"1613",
			"Leipzig",
			"19. September 1667",
			"1667",
			"Dresden",
			"Mann",
			"Dt. Dichter; Bibliothekar und Bürgermeister in Dresden"
		],
        [
			"Bressand, Friedrich Christian",
			"123060311",
			"2",
			"Friedrich Christian Bressand",
			"bressand",
			"",
			"1670",
			"1670",
			"Durlach",
			"1699",
			"1699",
			"Wolfenbüttel",
			"Mann",
			"Dichter, Theaterleiter"
		],
        [
			"Brockes, Barthold Heinrich d. Ä.",
			"118515586",
			"2",
			"Barthold Heinrich Brockes",
			"brockes",
			"",
			"22. September 1680",
			"1680",
			"Hamburg",
			"16. Januar 1747",
			"1747",
			"Hamburg",
			"Mann",
			"Dichter, Deutschland"
		],
        [
			"Brülow, Caspar",
			"119171082",
			"2",
			"Kaspar Brülow",
			"brülow",
			"",
			"18. September 1585",
			"1585",
			"Falckenberg bei Pyritz, Pommern",
			"14. Juli 1627",
			"1627",
			"",
			"Mann",
			"Neulateinischer deutscher Dramatiker ; Straßburg"
		],
        [
			"Buchner, Augustus",
			"118913859",
			"2",
			"August Buchner",
			"august buchner",
			"",
			"2. November 1591",
			"1591",
			"Dresden",
			"12. Februar 1661",
			"1661",
			"Apollensdorf",
			"Mann",
			"Dt. Philologe, Philosoph, Dichter, Rhetoriker; 17.11.1604 Schüler in Schulpforta; 19.11.1610 imm. in Wittenberg (19.03.1616 Magister); 1616 Prof. poes. und 1632 Prof. rhetor. in Wittenberg; 1641 Mitglied der Fruchtbringenden Gesellschaft (Der Genossene)"
		],
        [
			"Bucholtz, Andreas Heinrich",
			"118516744",
			"2",
			"Andreas Heinrich Bucholtz",
			"bucholtz",
			"",
			"1607",
			"1607",
			"Schöningen (Landkreis Helmstedt)",
			"1671",
			"1671",
			"Braunschweig",
			"Mann",
			"Dt. Dichter, Theologe und Philosoph; Gymnasialrektor in Lemgo; Professor phil. in Rinteln; Superintendent in Braunschweig ; Zwillingsbruder von Christoph Joachim Bucholtz (IDN 104319763); Dt. Schriftsteller ; Schriftsteller"
		],
        [
			"Butschky, Samuel d. J. von",
			"104320958",
			"2",
			"Samuel von Butschky",
			"butschky",
			"",
			"1612",
			"1612",
			"Breslau",
			"1678",
			"1678",
			"Breslau",
			"Mann",
			"Studium der Rechte in Wittenberg; Wechsel zur katholischen Kirche, vom Kaiser geadelt, Kaiserlicher Rat ; Verfasser religiöser Erbauungsschriften, eines «Schlüssels zur Rechtschreibung» und eines Briefstellers für verschiedene Lebensverhältnisse und Lebenslagen"
		],
        [
			"Callenbach, Frantz",
			"11851847X",
			"2",
			"Franz Callenbach",
			"callenbach",
			"",
			"10. Januar 1663",
			"1663",
			"Tauberbischofsheim-Dittwar",
			"3. Februar 1743",
			"1743",
			"Bamberg",
			"Mann",
			"Dt. Jesuit (SJ); Lehrer, Prediger und Autor satirischer Schuldramen der Barockzeit"
		],
        [
			"Canitz, Friedrich Rudolph Ludwig Freiherr von",
			"119171090",
			"2",
			"Friedrich von Canitz",
			"von canitz",
			"",
			"27. November 1654",
			"1654",
			"Berlin",
			"11. August 1699",
			"1699",
			"Berlin",
			"Mann",
			""
		],
        [
			"Corvinus, Gottlieb Siegmund",
			"100092438",
			"2",
			"Gottlieb Siegmund Corvinus",
			"siegmund corvinus",
			"",
			"15. Mai 1677",
			"1677",
			"Leipzig",
			"27. Januar 1746",
			"1746",
			"Leipzig",
			"Mann",
			"Schriftsteller"
		],
        [
			"Czepko von Reigersfeld, Daniel",
			"118677640",
			"2",
			"Daniel von Czepko",
			"czepko",
			"",
			"23. September 1605",
			"1605",
			"Koischwitz (Liegnitz)",
			"9. September 1660",
			"1660",
			"Wohlau",
			"Mann",
			"Medizin- und Jurastudium in Leipzig und Straßburg; Heirat mit Tochter eines Arztes in Schweidnitz; ab 1656 Regierungsrat in piastischen Diensten in Wohlau ; Sammeltätigkeit zugunsten des evangelischen Kirchenbaus; Bemühen um Reichensteiner Bergwerke; Verfasser zahlreicher geistlicher und weltlicher Dichtung ; seit 1630 Hauslehrer in Birawa u. Wreschin; 1633-1635 bei Baron Czigan v. Slupska in Dobroslawitz, Kr. Cosel ; aus Koischwitz bei Liegnitz; Sohn von Daniel Czepko (IDN 119384310); Dt. Dichter, Historiograph und Mystiker"
		],
        [
			"Dach, Simon",
			"11852321X",
			"2",
			"Simon Dach",
			"simon dach",
			"",
			"29. Juli 1605",
			"1605",
			"Memel",
			"15. April 1659",
			"1659",
			"Königsberg",
			"Mann",
			"Schulen in Königsberg, Wittenberg und Magdeburg; Theologie- und Philosophiestudium in Königsberg; Lehrtätigkeiten; seit 1639 Lehrstuhl für Poesie an Albertina; 1656 Rektor ; Mitglied des «Königsberger Dichterkreises» ; Dt. Dichter der Barockzeit; Liederkomponist; Hochschullehrer; Philosoph, Theologe; Professor für Poesie in Königsberg"
		],
        [
			"Dedekind, Constantin Christian",
			"120533405",
			"2",
			"Constantin Christian Dedekind",
			"christian dedekind",
			"",
			"1628",
			"1628",
			"Reinsdorf (Kyffhäuserkreis)",
			"1715",
			"1715",
			"Dresden",
			"Mann",
			"Dt. Dichter und Komponist"
		],
        [
			"Dilherr, Johann Michael",
			"118525697",
			"2",
			"Johann Michael Dilherr",
			"michael dilherr",
			"",
			"14. Oktober 1604",
			"1604",
			"Themar",
			"8. April 1669",
			"1669",
			"Nürnberg",
			"Mann",
			"Dt. ev. Theologe, Philologe, Kirchenliederdichter; Student in Leipzig, Wittenberg, Altdorf und Jena (1628 immatrikuliert), 1631 Magister in Jena; 1631-1642 Professor in Jena, ab 1635 Univ.-Rektor; ab 1642 Prediger in Nürnberg (1642-1669 Pfarrer der Sebalduskirche), gleichzeitig Reformator des Schulwesens und Stadtbibliothekar"
		],
        [
			"Drexel, Jeremias",
			"118680749",
			"2",
			"Jeremias Drexel",
			"jeremias drexel",
			"",
			"15. August 1581",
			"1581",
			"Augsburg",
			"19. April 1638",
			"1638",
			"München",
			"Mann",
			"Hofprediger des Kurfürsten Maximilian I."
		],
        [
			"Elmenhorst, Heinrich",
			"104319321",
			"2",
			"Heinrich Elmenhorst",
			"elmenhorst",
			"",
			"19. Oktober 1632",
			"1632",
			"Parchim",
			"21. Mai 1704",
			"1704",
			"Hamburg",
			"Mann",
			"Dt. ev. Theologe und Opernlibrettist"
		],
        [
			"Ettner, Johann Christoph",
			"118835629",
			"2",
			"Johann Christoph Ettner von Eiteritz",
			"von eiteritz",
			"",
			"16. März 1654",
			"1654",
			"Glogau",
			"22. Dezember 1724",
			"1724",
			"Breslau",
			"Mann",
			"Dt. Mediziner, Pharmazeut und Romanautor; 1708 geadelt"
		],
        [
			"Feind, Barthold d. J.",
			"118532294",
			"2",
			"Barthold Feind",
			"barthold feind",
			"",
			"1678",
			"1678",
			"Hamburg",
			"14. Oktober 1721",
			"1721",
			"Hamburg",
			"Mann",
			"Dt. Schriftsteller, Publizist und Librettist, auch Jurist und zuletzt Domvikar; Lic. iur.; Sohn des Lehrers Barthold F."
		],
        [
			"Felgenhauer, Paul",
			"123140269",
			"2",
			"Paul Felgenhauer",
			"felgenhauer",
			"",
			"1593",
			"1593",
			"Puschwitz",
			"",
			"",
			"Bremen",
			"Mann",
			"Böhmischer Kontroverstheologe, Theosoph, Chiliast, religiöser Schwärmer; aus Puschwitz (Buškovice) bei Podersam; emigrierte nach Amsterdam, später in Norddeutschland"
		],
        [
			"Finckelthaus, Gottfried",
			"11896173X",
			"2",
			"Gottfried Finckelthaus",
			"finckelthaus",
			"",
			"1614",
			"1614",
			"Leipzig",
			"1648",
			"1648",
			"Bautzen",
			"Mann",
			"Student.-burschikoser Barocklyriker"
		],
        [
			"Flayder, Friedrich Hermann",
			"118691643",
			"2",
			"Friedrich Hermann Flayder",
			"flayder",
			"",
			"10. Oktober 1596",
			"1596",
			"Tübingen",
			"6. April 1640",
			"1640",
			"Tübingen",
			"Mann",
			"Mag. Phil., Prof. Human. Univ. Tübingen; Dt. Dichter und Humanist ; Getauft am 10.10.1596 in Tübingen"
		],
        [
			"Fleming, Paul",
			"118533908",
			"2",
			"Paul Fleming",
			"paul fleming",
			"",
			"5. Oktober 1609",
			"1609",
			"Hartenstein (Landkreis Zwickau)",
			"2. April 1640",
			"1640",
			"Hamburg",
			"Mann",
			"Stand: 12.10.2021 ; Dt. Barockdichter, auch Liederdichter; Arzt; Hofjunker; Moskau- und Persienreise"
		],
        [
			"Francisci, Erasmus",
			"118534629",
			"2",
			"Erasmus Francisci",
			"erasmus francisci",
			"",
			"19. November 1627",
			"1627",
			"Lübeck",
			"20. Dezember 1694",
			"1694",
			"Nürnberg",
			"Mann",
			"Dt. Polyhistor, Jurist und Dichter; gräfl. Hohenlohescher Rat ; Schriftsteller ; Schriftsteller ; Christian Minsicht ist Pseudonym von Erasmus Francisci"
		],
        [
			"Franck, Johann",
			"104115319",
			"3",
			"Johann Franck",
			"johann franck",
			"johann(es)? franck",
			"1. Juni 1618",
			"1618",
			"Guben",
			"18. Juni 1677",
			"1677",
			"Guben",
			"Mann",
			"Dt. Jurist und Dichter (Kirchenlieder und weltl. Gedichte); Anwalt, Ratsherr, ab 1661 Bürgermeister in Guben; ab 1670 bürgerl. Landesältester der Niederlausitz ; Jurist"
		],
        [
			"Franck, Michael Erich",
			"120065908",
			"3",
			"Melisso",
			"erich franck",
			"(erich franck|melisso)",
			"1691",
			"1691",
			"",
			"1721",
			"1721",
			"",
			"Mann",
			"«Melisso» wird fälschlich auch Otto Philipp Virdung von Hartung zugeordnet"
		],
        [
			"Franckenberg, Abraham von",
			"118855050",
			"3",
			"Abraham von Frankenberg",
			"von frankenberg",
			"",
			"24. Juni 1593",
			"1593",
			"Bystre",
			"25. Juni 1652",
			"1652",
			"Bystre",
			"Mann",
			"aus Ludwigsdorf bei Oels/Schlesien; Dt. evangelischer Mystiker; Biograph und Herausgeber der Werke Jakob Böhmes; beigesetzt am 14.11.1652 in Breslau (Ort unsicher) ; Mystiker ; Pseud. lt. Holzmann/Bohatta; Weller; DBA  **    geb. und gest. in Ludwigsdorf bei Oels **  dt. prot. Mystiker. ; 2. Autor aus Freiburg,1673; übersetzte unter d. Pseud. Amadeus Friedleben «Der Verunruhigte holländ. Löw» ; Studium in Leipzig, Wittenberg, Jena und Frankfurt, Aufenthalte in Holland und Danzig ; Beschäftigung mit Jakob Böhme, Herausgabe seiner Schriften, Verfassung einer Lebensbeschreibung"
		],
        [
			"Freinsheim, Johannes",
			"116750146",
			"3",
			"Johann Freinsheim",
			"freinsheim",
			"",
			"16. November 1608",
			"1608",
			"Ulm",
			"31. August 1660",
			"1660",
			"Heidelberg",
			"Mann",
			"Dt. Jurist, Historiker und Historiograph, Philologe und Bibliothekar; Student in Marburg, Gießen und Straßburg; 1634 Sekretär im Archiv in Metz; 1637 Privatgelehrter in Straßburg; 1642 Prof. in Uppsala, 1647 Hofbibliothekar der schwedischen Königin Christina; 1651 Privatgelehrter in Worms; 1656 Kurfürstl. Rat und Honorarprofessor in Heidelberg; seit 1637 verheiratet mit Elisabeth Bernegger ; Bedeutender Vertreter der von M. Bernegger begründeten Straßburger Philologenschule"
		],
        [
			"Gerhardt, Paul",
			"118538659",
			"3",
			"Paul Gerhardt",
			"paul gerhardt",
			"",
			"12. März 1607",
			"1607",
			"Gräfenhainichen",
			"27. Mai 1676",
			"1676",
			"Lübben (Spreewald)",
			"Mann",
			""
		],
        [
			"Gläser, Enoch",
			"116649631",
			"3",
			"Enoch Gläser",
			"enoch gläser",
			"",
			"1628",
			"1628",
			"",
			"1668",
			"1668",
			"",
			"Mann",
			"aus Landeshut/Schlesien; Jurist; Dichter; Professor in Helmstedt und Hildesheim"
		],
        [
			"Glauber, Johann Rudolph",
			"118695304",
			"3",
			"Johann Rudolph Glauber",
			"rudolph glauber",
			"rudol(ph|f) glauber",
			"16. April 1604",
			"1604",
			"Karlstadt",
			"10. März 1670",
			"1670",
			"Amsterdam",
			"Mann",
			"auch in den Niederlanden tätig; Entdecker der medizinischen Wirkung von Natriumsulfat (Glaubersalz)"
		],
        [
			"Goldast von Haiminsfeld, Melchior",
			"118696130",
			"3",
			"Melchior Goldast",
			"melchior goldast",
			"",
			"6. Januar 1578",
			"1578",
			"Espen (Bischofszell)",
			"11. August 1635",
			"1635",
			"Gießen",
			"Mann",
			"Schweizer Jurist, Humanist, Polyhistor; 1594 in Ingolstadt und 1595 in Altdorf immatrikuliert, 1597 Magister in Altdorf, 1603 Dr. jur. in Heidelberg; lebte seit 1606 in Frankfurt a.M.; 1614 jur. Berater der Herzöge von Sachsen-Weimar; 1615 Hofrat und Rechtsberater in Bückeburg; ab 1624 im Dienst der Landgrafen von Hessen; seit 1630 Kanzler der Universität Gießen; seit 1612 verheiratet mit Sophia Ottilie Jeckel"
		],
        [
			"Greflinger, Georg",
			"118718622",
			"3",
			"Georg Greflinger",
			"georg greflinger",
			"",
			"1620",
			"1620",
			"",
			"1677",
			"1677",
			"Hamburg",
			"Mann",
			"aus Regensburg; unter dem Namen Seladon (Celadon) Mitglied des Elbschwanen-Ordens; Dünnhaupt ordnet Greflinger auch das Pseudonym David Seladon zu; Dt. Dichter; kaiserl. Notar ; Dichter, Notar"
		],
        [
			"Greiffenberg, Catharina Regina von",
			"118541978",
			"3",
			"Catharina Regina von Greiffenberg",
			"von greiffenberg",
			"",
			"1633",
			"1633",
			"Viehdorf-Seisenegg",
			"1694",
			"1694",
			"Nürnberg",
			"Frau",
			"Geistlich-protestantischee Lyrikerin; ab 1679 in Nürnberg tätig; Mitglied der Deutschgesinnten Genossenschaft"
		],
        [
			"Gretser, Jacob",
			"118542087",
			"3",
			"Jacob Gretser",
			"jacob gretser",
			"",
			"27. März 1562",
			"1562",
			"Markdorf",
			"29. Januar 1625",
			"1625",
			"Ingolstadt",
			"Mann",
			"Dt. Jesuit; Theologe und Dichter; wirkte in Markdorf, Freiburg/Schweiz (1584-1586), Prof. in Ingolstadt"
		],
        [
			"Grimmelshausen, Hans Jacob Christoph von",
			"118542273",
			"3",
			"Hans Jakob Christoffel von Grimmelshausen",
			"von grimmelshausen",
			"",
			"XX.XX.1622",
			"1622",
			"Gelnhausen",
			"17. August 1676",
			"1676",
			"Renchen",
			"Mann",
			"Dichter, Deutschland"
		],
        [
			"Grob, Johann",
			"10014568X",
			"3",
			"Johann Grob",
			"johann grob",
			"",
			"16. September 1643",
			"1643",
			"Oberglatt (Sankt Gallen)",
			"1. April 1697",
			"1697",
			"",
			"Mann",
			"Dichter, Satiriker"
		],
        [
			"Gryphius, Andreas",
			"118543032",
			"3",
			"Andreas Gryphius",
			"gryphius",
			"",
			"2. Oktober 1616",
			"1616",
			"Glogau",
			"16. Juli 1664",
			"1664",
			"Glogau",
			"Mann",
			"Vater: Paul Greif (gest. 1621) Mutter: Anna (gest. 1628) in 2. Ehe mit Michael Eder verheiratet. Bruder: Paul Greif (evang.Pfarrer, gest. 1640) Schwester: Anna Maria (gest. 1640) ; Dt. Dichter ; Dichter, Deutschland"
		],
        [
			"Gryphius, Christian",
			"119209322",
			"3",
			"Christian Gryphius",
			"gryphius",
			"",
			"29. September 1649",
			"1649",
			"Fraustadt",
			"6. März 1706",
			"1706",
			"Breslau",
			"Mann",
			"Deutscher Pädagoge und Schuldramatiker"
		],
        [
			"Günther, Johann Christian",
			"11854327X",
			"3",
			"Johann Christian Günther",
			"christian günther",
			"",
			"8. April 1695",
			"1695",
			"Striegau",
			"15. März 1723",
			"1723",
			"Jena",
			"Mann",
			"Schlesischer Dichter, Lyriker; lebte u.a. in Hirschberg, Schmiedeberg und in Oberschlesien"
		],
        [
			"Hallmann, Johann Christian",
			"118701142",
			"3",
			"Johann Christian Hallmann",
			"christian hallmann",
			"",
			"1640",
			"1640",
			"Breslau",
			"1704",
			"1704",
			"Wien",
			"Mann",
			""
		],
        [
			"Hancke, Gottfried Benjamin",
			"129918563",
			"3",
			"Gottfried Benjamin Hancke",
			"benjamin hancke",
			"",
			"1695",
			"1695",
			"",
			"1750",
			"1750",
			"",
			"Mann",
			"Verfasser geistlicher und weltlicher Gedichte"
		],
        [
			"Happel, Eberhard Werner",
			"118720309",
			"3",
			"Eberhard Werner Happel",
			"werner happel",
			"",
			"10. August 1647",
			"1647",
			"Kirchhain",
			"15. Mai 1690",
			"1690",
			"Hamburg",
			"Mann",
			""
		],
        [
			"Harsdörffer, Georg Philipp",
			"118546139",
			"3",
			"Georg Philipp Harsdörffer",
			"harsdörffer",
			"",
			"1. November 1607",
			"1607",
			"Nürnberg-Fischbach",
			"17. September 1658",
			"1658",
			"Nürnberg",
			"Mann",
			"Deutscher Dichter; Ratsherr; 1644 Begründer des Pegnesischen Blumenordens in Nürnberg ; Nürnberger Patrizier"
		],
        [
			"Haugwitz, August Adolph von",
			"100352952",
			"3",
			"August Adolf von Haugwitz",
			"von haugwitz",
			"",
			"1645",
			"1645",
			"",
			"1706",
			"1706",
			"",
			"Mann",
			""
		],
        [
			"Heermann, Johannes",
			"11870950X",
			"3",
			"Johann Heermann",
			"heermann",
			"",
			"11. Oktober 1585",
			"1585",
			"Raudten",
			"17. Februar 1647",
			"1647",
			"Lissa",
			"Mann",
			"Deutscher evangelischer Theologe und Liederdichter; Schüler am Gymnasium Brieg/Schlesien; 1608 Gekrönter Dichter; ab 1611 Pfarrer in Köben a.d. Oder; 1638 Rückzug nach Lissa"
		],
        [
			"Heidenreich, David Elias",
			"115834192",
			"3",
			"David Elias Heidenreich",
			"elias heidenreich",
			"david( elias)? heidenreich",
			"21. Januar 1638",
			"1638",
			"Leipzig",
			"6. Juni 1688",
			"1688",
			"Weißenfels",
			"Mann",
			"deutscher Jurist, Poet, Dramatiker und Übersetzer; Hof- und Konsistorialrat in Weißenfels; Mitglied der Fruchtbringenden Gesellschaft (Der Willige)"
		],
        [
			"Hille, Carl Gustav von",
			"129300454",
			"3",
			"Karl Gustav von Hille",
			"gustav von hille",
			"",
			"1590",
			"1590",
			"Suchan (Polen)",
			"1647",
			"1647",
			"",
			"Mann",
			"Dt. Poet, Mitglied der Fruchtbringenden Gesellschaft; geb. in Zachan (Pommern), gest. in Allendorf oder Allersheim bei Holzminden"
		],
        [
			"Hoburg, Christian",
			"121145905",
			"3",
			"Christian Hoburg",
			"christian hoburg",
			"",
			"23. Juli 1607",
			"1607",
			"Lüneburg",
			"29. Oktober 1675",
			"1675",
			"Altona",
			"Mann",
			""
		],
        [
			"Höck, Theobald",
			"129212822",
			"3",
			"Theobald Hock",
			"theobald hock",
			"",
			"1573",
			"1573",
			"Limbach (Homburg, Saar)",
			"1619",
			"1619",
			"",
			"Mann",
			"geb. in Limbach bei Homburg; Dt. Diplomat und Dichter"
		],
        [
			"Höveln, Conrad von",
			"121781402",
			"3",
			"Conrad von Höveln",
			"von höveln",
			"",
			"1630",
			"1630",
			"",
			"1689",
			"1689",
			"",
			"Mann",
			"Mitglied des Elbschwanenordens Hamburg; Dt. Schriftsteller und Geschichtsschreiber, lebte ab 1668 in Dänemark"
		],
        [
			"Hoffmannswaldau, Christian Hoffmann von",
			"118706187",
			"3",
			"Christian Hofmann von Hofmannswaldau",
			"hofmannswaldau",
			"",
			"25. Dezember 1617",
			"1617",
			"Breslau",
			"18. April 1679",
			"1679",
			"Breslau",
			"Mann",
			"Dt. Dichter"
		],
        [
			"Hohberg, Wolfgang Helmhard Freiherr von",
			"118774735",
			"3",
			"Wolf Helmhardt von Hohberg",
			"von hohberg",
			"",
			"20. Oktober 1612",
			"1612",
			"Lengenfeld",
			"28. Januar 1688",
			"1688",
			"Regensburg",
			"Mann",
			"Österr. protestant. Schriftsteller; Mitglied der Fruchtbringenden Gesellschaft (Der Sinnreiche)"
		],
        [
			"Homburg, Ernst Christoph",
			"100818684",
			"3",
			"Ernst Christoph Homburg",
			"christoph homburg",
			"",
			"1605",
			"1605",
			"Amt Creuzburg- Mihla",
			"1681",
			"1681",
			"Naumburg (Saale)",
			"Mann",
			"Dt. Jurist und Poet; Mitglied der Fruchtbringenden Gesellschaft; Gerichtsschreiber in Naumburg"
		],
        [
			"Hoyer, Anna Ovena",
			"122335430",
			"3",
			"Anna Ovena Hoyer",
			"ovena hoyer",
			"anna( ovena)? hoyer",
			"XX.XX.1584",
			"1584",
			"Koldenbüttel",
			"27. November 1655",
			"1655",
			"",
			"Frau",
			"Tochter des Astronomen Johann Oven aus Koldenbüttel (Schleswig), verheiratet mit Hermann Hoyer; gest. in Stockholm; Dt. Dichterin, religiöse Sektiererin"
		],
        [
			"Hudemann, Heinrich d. J.",
			"1055526412",
			"3",
			"Heinrich Hudemann",
			"heinrich hudemann",
			"",
			"1597",
			"1597",
			"Beidenfleth",
			"1628",
			"1628",
			"",
			"Mann",
			"Studierte Theologie an der Univ. Rostock. War protestantischer Geistlicher, Diakon in Wewelsfleth. Kaiserliche katholische Offiziere erzwangen Gifteinnahme ; Lit: Moerke, Ulrich. Die Anfänge der weltlichen Barocklyrik in Schleswig-Holstein. Hudemann, Rist, Lund. 1972"
		],
        [
			"Hübner, Tobias",
			"120079291",
			"3",
			"Tobias Hübner",
			"tobias hübner",
			"",
			"5. April 1578",
			"1578",
			"Halle (Saale)",
			"5. Mai 1636",
			"1636",
			"Dessau",
			"Mann",
			"Dt. Jurist, Staatsmann, Übersetzer und Dichtungstheoretiker; Geheimrat, Hofmeister sowie Kammer- und Justizrat in Anhalt-Dessau; ab 1619 Mitglied der Fruchtbringenden Gesellschaft (Der Nutzbare); Herr auf Reupzig und Beesen"
		],
        [
			"Hunold, Christian Friedrich",
			"118554840",
			"3",
			"Christian Friedrich Hunold",
			"friedrich hunold",
			"",
			"1680",
			"1680",
			"Wandersleben",
			"16. August 1721",
			"1721",
			"Halle (Saale)",
			"Mann",
			"Gab  1707 die Leipziger Rhetorikvorlesungen von Erdmann Neumeister (1671-1742) unter dem Titel «Die allerneueste Art zur reinen und galanten Poesie zu gelangen» unter eigenem Namen heraus und überarbeitete sie wahrscheinlich auch. Die Anteile der beiden Autoren lassen sich nicht mehr mit Gewißheit unterscheiden."
		],
        [
			"Kaldenbach, Christoph d. Ä.",
			"118559486",
			"3",
			"Christoph Kaldenbach",
			"kaldenbach",
			"",
			"11. August 1613",
			"1613",
			"Schwiebus",
			"16. Juli 1698",
			"1698",
			"Tübingen",
			"Mann",
			"Dt. Historiker, Philologe und ev. Theologe, Poeta laureatus; Student in Frankfurt (Oder) und Königsberg; 1639 Konrektor und 1645 Prorektor der Lateinschule in Königsberg; 1651 Prof. graec. an der Univ. Königsberg; seit 1656 Lehrstuhl für Rhetorik, Dichtkunst und Geschichte in Tübingen"
		],
        [
			"Kempe, Martin",
			"119511231",
			"3",
			"Martin von Kempe",
			"martin von kempe",
			"",
			"5. Juni 1642",
			"1642",
			"Königsberg",
			"31. Juli 1683",
			"1683",
			"Königsberg",
			"Mann",
			"aDt. Historiograph, Übersetzer und Poet; Mitglied des Pegnesischen Blumenordens (bis 1669 als Damon), der Fruchtbringenden Gesellschaft (Der Erkorene) sowie der Deutschgesinnten Genossenschaft (Der Unsterbliche) und des Elbschwanenordens (Kleodor)"
		],
        [
			"Kepler, Johannes",
			"118561448",
			"3",
			"Johannes Kepler",
			"johannes kepler",
			"",
			"27. Dezember 1571",
			"1571",
			"Weil der Stadt",
			"15. November 1630",
			"1630",
			"Regensburg",
			"Mann",
			"lebte ab 1594 im damaligen Österreich, ab 1628 in Schlesien; Theologiestudium; Weil der Stadt, Tübingen, Graz, Prag, Linz, Sagan/Schlesien (Wirkungsorte) ; Dt. Astronom und Mathematiker"
		],
        [
			"Kindermann, Balthasar",
			"118562185",
			"3",
			"Balthasar Kindermann",
			"balthasar kindermann",
			"",
			"10. April 1636",
			"1636",
			"Zittau",
			"12. Februar 1706",
			"1706",
			"Magdeburg",
			"Mann",
			"Stud. Univ. Wittenberg, Magister ebd. (1657); Konrektor der Saldernschen Schule in Brandenburg/ H. (ab 1659); Diakon St. Johannis Magdeburg (1667-1672); Oberpfr. St. Ulrich u. Levin ebd. (1672-1706); Dichter; Mitglied des Elbschwanenordens (seit 1659)"
		],
        [
			"Kircher, Athanasius",
			"118562347",
			"3",
			"Athanasius Kircher",
			"athanasius kircher",
			"",
			"2. Mai 1602",
			"1602",
			"Geisa",
			"28. November 1680",
			"1680",
			"Rom",
			"Mann",
			"Deutscher katholischer Theologe, Jesuit (SJ) und Universalgelehrter; Lehrer für Mathematik, Hebräisch und Syrisch in Heiligenstadt; 1628 Priester und Professor für Mathematik und Ethik an der Universität Würzburg; seit 1635 am Collegium Romanum (Gregoriana)"
		],
        [
			"Klaj, Johann",
			"118723324",
			"4",
			"Johann Klaj",
			"johann klaj",
			"",
			"1616",
			"1616",
			"Meißen",
			"16. Februar 1656",
			"1656",
			"Kitzingen",
			"Mann",
			"Dt. ev. Theologe und Poet; Student in Wittenberg und Leipzig; Dichter und Schriftsteller in Nürnberg, 1644 Mitgründer des Pegnesischen Blumenordens; ab 1650 Pfarrer in Kitzingen"
		],
        [
			"Knorr von Rosenroth, Christian",
			"118723863",
			"4",
			"Christian Knorr von Rosenroth",
			"knorr von rosenroth",
			"",
			"1636",
			"1636",
			"Raudten",
			"1689",
			"1689",
			"Sulzbach (Oberpfalz)",
			"Mann",
			"Dt. Kanzler, Theosoph, Polyhistor, Dichter und Schriftsteller"
		],
        [
			"König, Johann Ulrich von",
			"118777661",
			"4",
			"Johann Ulrich von König",
			"ulrich von könig",
			"",
			"8. Oktober 1688",
			"1688",
			"Esslingen am Neckar",
			"14. März 1744",
			"1744",
			"Dresden",
			"Mann",
			"Mitbegründer der «Deutschübenden Gesellschaft» in Hamburg (1715); Ernennung zum Königl. Geheimsekretär und Hofpoeten in Dresden (1719); ab 1729 Geheimrat und Zeremonienmeister in Dresden; 1740 geadelt"
		],
        [
			"Kongehl, Michael",
			"12672668X",
			"4",
			"Michael Kongehl",
			"kongehl",
			"",
			"1646",
			"1646",
			"Kreuzburg (Ostpreußen)",
			"1710",
			"1710",
			"Königsberg",
			"Mann",
			"aus Creuzburg in Preussen; Mitglied des Pegnesischen Blumenordens in Nürnberg; Preußischer Kurfürstlicher Sekretär; Bürgermeister; Dichter"
		],
        [
			"Kormart, Christoph",
			"121834514",
			"4",
			"Christoph Kormart",
			"kormart",
			"",
			"22. Juli 1644",
			"1644",
			"Leipzig",
			"18. Februar 1701",
			"1701",
			"Dresden",
			"Mann",
			"Dt. Jurist, Poet sowie Übersetzer franz. und niederländ. Dramen"
		],
        [
			"Kornfeld, Theodor",
			"124689035",
			"4",
			"Theodor Kornfeld",
			"theodor kornfeld",
			"",
			"1636",
			"1636",
			"",
			"1698",
			"1698",
			"",
			"Mann",
			"aus Herford; 1665 theol. Respondent in Jena; Magister in Jena; Rektor in Osnabrück; Prediger, Poet"
		],
        [
			"Kuefstein, Johann Ludwig Reichsgraf von",
			"118567535",
			"4",
			"Hans Ludwig von Kuefstein",
			"von kuefstein",
			"",
			"1582",
			"1582",
			"",
			"1656",
			"1656",
			"",
			"Mann",
			"Landeshauptmann von Oberösterreich, Diplomat und Übersetzer"
		],
        [
			"Kuen, Johannes",
			"121689530",
			"4",
			"Johannes Khuen",
			"khuen",
			"",
			"1606",
			"1606",
			"Moosach (München)",
			"1675",
			"1675",
			"München",
			"Mann",
			""
		],
        [
			"Kuhlmann, Quirinus",
			"11872522X",
			"4",
			"Quirinus Kuhlmann",
			"quirinus kuhlmann",
			"",
			"25. Februar 1651",
			"1651",
			"Breslau",
			"4. Oktober 1689",
			"1689",
			"Moskau",
			"Mann",
			"Spiritualist, Visionär, Poet; Verehrer Jakob Böhmes; Sohn des gleichnamigen Breslauer Kaufmanns; Gymnasium in Breslau; Abbruch des Jurastudiums in Jena (1670 imm.); ab 1673 in Leiden; danach in London; von ca. 1675 bis ca. 1684 befreundet mit Friedrich Breckling; Reisen u.a. nach Syrien und Konstantinopel; 1689 in Russland, am  4. Oktober 1689 in Moskau als Ketzer verbrannt ; Lyriker, Schlesien, Russland"
		],
        [
			"Kuhnau, Johann",
			"118567934",
			"4",
			"Johann Kuhnau",
			"johann kuhnau",
			"johann(es)? kuhnau",
			"6. April 1660",
			"1660",
			"Geising",
			"5. Juni 1722",
			"1722",
			"Leipzig",
			"Mann",
			"Dt. Jurist; Komponist, Musiker u. Musiktheoretiker; Chorleiter u. Organist in Zittau; Anwalt in Leipzig; Thomaskantor u. Universitätsmusikdirektor in Leipzig ; Komponist, Schriftsteller"
		],
        [
			"Kunckel, Johann",
			"11872536X",
			"4",
			"Johannes Kunckel",
			"johannes junckel",
			"johann(es)? kunckel",
			"1630",
			"1630",
			"Hütten (Rendsburg-Eckernförde)",
			"20. März 1703",
			"1703",
			"",
			"Mann",
			"Dt. Alchimist und Glasmacher; stand im Dienst mehrerer dt. Fürsten sowie des schwedischen Königs Karl XI.; geadelt als Ritter von Löwenstern; geboren in Hütten (oder in Wittenberg/Plön), Todesort unbekannt (Stockholm oder Pernau) ; Chemiker"
		],
        [
			"Lassenius, Johannes",
			"104247533",
			"4",
			"Johannes Lassenius",
			"johannes lassenius",
			"johann(es)? lassenius",
			"26. April 1636",
			"1636",
			"Waldow (Pommern)",
			"29. August 1692",
			"1692",
			"Kopenhagen",
			"Mann",
			"Dt. ev.-luth. Theologe und Erbauungsschriftsteller; Prof. in Kopenhagen"
		],
        [
			"Lauremberg, Johannes",
			"118726714",
			"4",
			"Johann Lauremberg",
			"lauremberg",
			"johann(es)? lauremberg",
			"1590",
			"1590",
			"Rostock",
			"1659",
			"1659",
			"Sorø",
			"Mann",
			"Dt. Späthumanist, Schriftsteller und Satirendichter, Prof. für Poesie ; Schriftsteller"
		],
        [
			"Lauremberg, Peter",
			"100810977",
			"4",
			"Peter Lauremberg",
			"lauremberg",
			"",
			"26. August 1585",
			"1585",
			"Rostock",
			"13. Mai 1639",
			"1639",
			"Rostock",
			"Mann",
			"aus Rostock; Respondent in Rostock, Leiden, Löwen, Paris u.a.; Mediziner; Physiker; Mathematiker; Poet; Professor in Hamburg und Rostock ; Mediziner, Astronom, Mathematiker, Philosoph, Schriftsteller"
		],
        [
			"Laurentius von Schnüffis",
			"118726765",
			"4",
			"Laurentius, von Schnüffis",
			"von schnüffis",
			"",
			"1633",
			"1633",
			"",
			"1702",
			"1702",
			"",
			"Mann",
			"Kapuziner ; Dt. Komponist, Schauspieler, Lyriker; Kapuziner"
		],
        [
			"Lehms, Georg Christian",
			"104268034",
			"4",
			"Georg Christian Lehms",
			"christian lehms",
			"",
			"1684",
			"1684",
			"",
			"1717",
			"1717",
			"",
			"Mann",
			""
		],
        [
			"Logau, Friedrich von",
			"11872889X",
			"4",
			"Friedrich von Logau",
			"von logau",
			"",
			"XX.01.1605",
			"1605",
			"Brockut",
			"24. Juli 1655",
			"1655",
			"Liegnitz",
			"Mann",
			"Dt. Dichter des Barock; Regierungsrat; Liederdichter; Mitglied der Fruchtbringenden Gesellschaft, Meister des Epigramms"
		],
        [
			"Lohenstein, Daniel Casper von",
			"118574078",
			"4",
			"Daniel Casper von Lohenstein",
			"von lohenstein",
			"",
			"5. Januar 1635",
			"1635",
			"Nimptsch",
			"28. April 1683",
			"1683",
			"Breslau",
			"Mann",
			"Dt. Dichter und Jurist; Student in Leipzig und Tübingen; Stadtsyndikus in Breslau; hieß bis 1670 Casper (bzw. Caspari), dann geadelt"
		],
        [
			"Ludwig, Fürst von Anhalt-Köthen",
			"118574868",
			"4",
			"Ludwig, Anhalt-Köthen, Fürst",
			"ludwig von anhalt",
			"",
			"17. Juni 1579",
			"1579",
			"Dessau",
			"7. Januar 1650",
			"1650",
			"Köthen (Anhalt)",
			"Mann",
			"ab 1606 regierender Fürst von Anhalt-Köthen; Gründer der Fruchtbringenden Gesellschaft (Der Nehrende)"
		],
        [
			"Lund, Zacharias",
			"121448231",
			"4",
			"Zacharias Lund",
			"zacharias lund",
			"",
			"5. April 1608",
			"1608",
			"Nybøl",
			"8. Juni 1667",
			"1667",
			"Kopenhagen",
			"Mann",
			"Dän. Lyriker und Dramatiker, Bibliothekar, Lehrer"
		],
        [
			"Männling, Johann Christoph",
			"129376361",
			"4",
			"Johann Christoph Männling",
			"chsristoph männling",
			"",
			"1658",
			"1658",
			"Wabnitz (Schlesien)",
			"1723",
			"1723",
			"",
			"Mann",
			"Studium in Breslau und Wittenberg (1678 imm.); kaiserl. gekrönter Poet; 1688-1700 ev. Pfarrer in Kreuzburg/Oberschlesien (poln. Kluczbork), dann Exulant; 1701-1723 Diakon an St. Johannis und Pastor an der Augustinerkirche sowie königl. preuß. Garnisonsprediger in Stargard/Pommern"
		],
        [
			"Magdalena Sibylla, Herzogin von Württemberg",
			"122063317",
			"4",
			"Magdalena Sibylla, Württemberg, Herzogin, 1652-1712",
			"magdalena sibylla",
			"",
			"28. April 1652",
			"1652",
			"Darmstadt",
			"11. August 1712",
			"1712",
			"Kirchheim unter Teck",
			"Frau",
			"Tochter Landgraf Ludwigs VI. von Hessen-Darmstadt; seit 1673 Ehefrau des Herzogs Wilhelm Ludwig von Württemberg; 1677-1693 Witwe und Regentin"
		],
        [
			"Marperger, Paul Jacob",
			"10422262X",
			"4",
			"Paul Jacob Marperger",
			"jacob marperger",
			"",
			"27. Juni 1656",
			"1656",
			"Nürnberg",
			"27. Oktober 1730",
			"1730",
			"Dresden",
			"Mann",
			"Gelehrter für Handlungswissenschaft; Kameralist, 1708 in die Königlich Preußische Gesellschaft der Wissenschaften aufgenommen"
		],
        [
			"Masen, Jacob d. J.",
			"118782444",
			"4",
			"Jacob Masen",
			"jacob masen",
			"",
			"1606",
			"1606",
			"Dahlen bei Mönchen-Gladbach",
			"1681",
			"1681",
			"Köln",
			"Mann",
			"Dt. Jesuit"
		],
        [
			"Meichel, Joachim",
			"100272568",
			"4",
			"Joachim Meichel",
			"moachim meichel",
			"",
			"1590",
			"1590",
			"",
			"14. August 1637",
			"1637",
			"",
			"Mann",
			"Dichter, Übersetzer ; Dichter"
		],
        [
			"Meier, Joachim",
			"118732595",
			"4",
			"Joachim Meier",
			"joachim meier",
			"",
			"10. August 1661",
			"1661",
			"Perleberg",
			"2. April 1732",
			"1732",
			"Göttingen",
			"Mann",
			"Dt. Jurist, Pädagoge und Dichter; Promotion 1707; Kantor und Professor am Göttinger Gymnasium (1686-1717), lehrte Musik, Geschichte und Geographie; praktizierte nach seiner Emeritierung als Rechtsberater"
		],
        [
			"Meyfart, Johann Matthäus",
			"118582038",
			"4",
			"Johann Matthäus Meyfart",
			"meyfart",
			"",
			"9. November 1590",
			"1590",
			"Jena",
			"26. Januar 1642",
			"1642",
			"Erfurt",
			"Mann",
			"Dt. ev. Theologe, Pädagoge, Erbauungsschriftsteller und Liederdichter; 1602 Schüler am Gymnasium Gotha; 1608 Student in Jena, 1613 Magister; Hofmeister; 1614 Student in Wittenberg; 1616 Adjunkt der Theol. Fakultät Jena; 1617-1623  Prof.  theol. am Gymnasium Casimirianum in Coburg, 1623-1632 dort auch Rektor; 1633-1642 Prof. theol. an der Univ. Erfurt, 1634/35 auch Rektor; 1636-1642 zugleich Oberpfarrer an der Predigerkirche Erfurt und Senior des Ev. Ministeriums"
		],
        [
			"Mitternacht, Johann Sebastian",
			"118582879",
			"4",
			"Johann Sebastian Mitternacht",
			"sebastian mitternacht",
			"",
			"30. März 1613",
			"1613",
			"Hardisleben",
			"25. Juli 1679",
			"1679",
			"Zeitz",
			"Mann",
			"Dt. ev. Theologe, Philologe, Pädagoge u. Dichter; Student in Jena u. Wittenberg, 1636: Magister; 1638: Pfarrer in Teutleben u. Lehrer in Buttstädt; 1642: Rektor der Naumburger Stadtschule; 1646: Rektor am Gymnasium Rutheneum Gera; 1667-1668: Stiftssuperintendent in Neustadt (Orla); 1668-1679: Oberhofprediger u. Stiftssuperintendent in Zeitz, Assessor im Stiftskonsistorium in Zeitz; Mitglied der Deutschgesinnten Genossenschaft (Der Erfreuliche); Poeta laureatus"
		],
        [
			"Morhof, Daniel Georg",
			"118784919",
			"4",
			"Daniel Georg Morhof",
			"georg morhof",
			"",
			"6. Februar 1639",
			"1639",
			"Wismar",
			"30. Juli 1691",
			"1691",
			"Lübeck",
			"Mann",
			"Dt. Literaturhistoriker und Jurist; Prof. an der Univ. Rostock und Kiel"
		],
        [
			"Moscherosch, Johann Michael",
			"118641182",
			"4",
			"Johann Michael Moscherosch",
			"moscherosch",
			"",
			"5. März 1601",
			"1601",
			"Willstätt",
			"4. April 1669",
			"1669",
			"Worms",
			"Mann",
			"Dichter, Mitglied der Fruchtbringenden Gesellschaft"
		],
        [
			"Mühlpfort, Heinrich",
			"124365329",
			"4",
			"Heinrich Mühlpfort",
			"mühlpfort",
			"",
			"10. Juli 1639",
			"1639",
			"Breslau",
			"1. Juli 1681",
			"1681",
			"Breslau",
			"Mann",
			""
		],
        [
			"Neander, Joachim",
			"118586688",
			"4",
			"Joachim Neander",
			"joachim neander",
			"",
			"XX.XX.1650",
			"1650",
			"Bremen",
			"31. Mai 1680",
			"1680",
			"Bremen",
			"Mann",
			"Namensgeber des von ihm häufig durchwanderten heutigen Neandertals"
		],
        [
			"Neukirch, Benjamin",
			"118785990",
			"4",
			"Benjamin Neukirch",
			"benjamin neukirch",
			"",
			"27. März 1665",
			"1665",
			"Roniken (Fürstentum Glogau)",
			"15. August 1729",
			"1729",
			"Ansbach",
			"Mann",
			"Dt. Jurist und Dichter; 1687 Advokat in Breslau; ab 1691 Dozent für Poesie in Frankfurt (Oder) und Halle (Saale); ab 1703 Professor an der Ritterakademie in Berlin; ab 1718 Hofrat und Erzieher des Erbprinzen in Ansbach"
		],
        [
			"Neumark, Georg",
			"118587404",
			"4",
			"Georg Neumark",
			"georg neumark",
			"",
			"16. März 1621",
			"1621",
			"Bad Langensalza",
			"8. Juli 1681",
			"1681",
			"Weimar",
			"Mann",
			"Dt. Dichter und Komponist von Kirchenliedern; ab 1640 Jurastudium in Königsberg; 1652 Kanzleiregistrator und Bibliothekar bei Herzog Wilhelm IV. von Sachsen-Weimar, ab 1653 Mitglied der Fruchtbringenden Gesellschaft (Der Sprossende), ab 1679 Mitglied des Pegnesischen Blumenordens (Thyrsis)"
		],
        [
			"Olearius, Adam",
			"118736256",
			"4",
			"Adam Olearius",
			"adam olearius",
			"",
			"1599",
			"1599",
			"Aschersleben",
			"22. Februar 1671",
			"1671",
			"Schleswig (Stadt)",
			"Mann",
			"Herzogl.-holsteinischer Rat, Bibliothekar und Mathematiker auf Schloss Gottdorf; Mitglied der Fruchtbringenden Gesellschaft"
		],
        [
			"Opitz, Martin",
			"118590111",
			"4",
			"Martin Opitz",
			"martin opitz",
			"",
			"23. Dezember 1597",
			"1597",
			"Bunzlau",
			"20. August 1639",
			"1639",
			"Danzig",
			"Mann",
			"Dichter, herzogl. schlesischer Rat, Sekretär und Historiograph des polnischen Königs Wladyslaw IV. ; Gymnasien in Bunzlau, Breslau und Beuthen a.d.O.; Studium in Frankfurt/O. und Heidelberg; geadelt und von Kaiser Ferdinand II. zum Dichter gekrönt; lebte seit 1635 in Danzig als Hofhistoriograph des Königs Wladislaw IV. von Polen; Gründer der «Ersten schlesischen Dichterschule»"
		],
        [
			"Pastorius, Franz Daniel",
			"12019323X",
			"4",
			"Franz Daniel Pastorius",
			"daniel pastorius",
			"",
			"1651",
			"1651",
			"Sommerhausen",
			"1719",
			"1719",
			"Germantown, Pa.",
			"Mann",
			"Dt. Jurist und Barockschriftsteller; Gründer und Friedensrichter von Germantown (Philadelphia)"
		],
        [
			"Paullini, Christian Franz",
			"118739581",
			"4",
			"Christian Franz Paullini",
			"franz paullini",
			"",
			"25. Februar 1643",
			"1643",
			"Eisenach",
			"10. Juni 1712",
			"1712",
			"Eisenach",
			"Mann",
			"Studium in Königsberg, Kopenhagen, Kiel, Rostock, Hamburg, in Wittenberg Magister; Bildungsreisen; Dr. med. in Leiden; 1673-1675 Arzt in Altona; 1675 Comes palatin. caesar., Leibarzt des Bischofs zu Münster und Historiograph; 1678 im Dienst des Herzogs von Braunschweig-Wolfenbüttel; ab 1689 Stadtarzt in Eisenach; Mitglied der Fruchtbringenden Gesellschaft (1672), des Pegnesischen Blumenordens u. der Deutschen Akad. der Naturforscher Leopoldina (1675); rege schriftstellerische Tätigkeit auf den verschiedensten Gebieten; Begründer des Historisches Reichscollegs"
		],
        [
			"Peucker, Nicolaus",
			"122447972",
			"4",
			"Nicolaus Peucker",
			"peucker",
			"",
			"1625",
			"1625",
			"Kolbnitz bei Jauer/Schlesien",
			"1674",
			"1674",
			"",
			"Mann",
			"Dt. Stadtrichter, Ratskämmerer und Dichter; Gymnasiast in Breslau; Student in Frankfurt (Oder); ab ca. 1650 Jurist in Cölln (Spree)"
		],
        [
			"Postel, Christian Heinrich",
			"118741632",
			"4",
			"Christian Heinrich Postel",
			"heinrich postel",
			"",
			"11. Oktober 1658",
			"1658",
			"Freiburg, Elbe",
			"22. März 1705",
			"1705",
			"Hamburg",
			"Mann",
			"Dt. Jurist u. Dichter, Verf. zahlreicher Opernlibretti"
		],
        [
			"Praetorius, Johann",
			"11859611X",
			"5",
			"Johannes Praetorius",
			"johannes praetorius",
			"",
			"22. Oktober 1630",
			"1630",
			"Kalbe-Zethlingen",
			"25. Oktober 1680",
			"1680",
			"Leipzig",
			"Mann",
			"Poeta laureatus; aus Zethlingen in der Altmark; Vielschreiber; Verf. von «Disquisitio de magia divinatrice ...» lt. Dünnhaupt (angebl. Verf.: Franciscus Moncaeus) ; Schriftsteller"
		],
        [
			"Prasch, Johann Ludwig",
			"100230792",
			"5",
			"Johann Ludwig Prasch",
			"ludwig prasch",
			"",
			"1637",
			"1637",
			"Regensburg",
			"12. Juni 1690",
			"1690",
			"Regensburg",
			"Mann",
			"Dt. Jurist, Politiker, Sprachforscher und Dichter; Syndikus, Ratsherr, später Bürgermeister in Regensburg, Gesandter beim Reichstag"
		],
        [
			"Printz, Wolfgang Caspar",
			"118939599",
			"5",
			"Wolfgang Caspar Printz",
			"caspar printz",
			"",
			"1641",
			"1641",
			"Waldthurn",
			"1717",
			"1717",
			"Sorau",
			"Mann",
			"Dt. Komponist, Musiktheoretiker und Schriftsteller ; Mimnermo ist ein Pseudonym"
		],
        [
			"Prokop von Templin",
			"118834517",
			"5",
			"Prokop, von Templin",
			"prokop von templin",
			"",
			"1609",
			"1609",
			"",
			"1680",
			"1680",
			"",
			"Mann",
			"Kapuziner der Österreichischen Provinz; 1661 Prediger in Passau; Dt. Kapuziner"
		],
        [
			"Rachel, Joachim",
			"124615589",
			"5",
			"Joachim Rachel",
			"joachim rachel",
			"",
			"28. Februar 1618",
			"1618",
			"Lunden",
			"3. März 1669",
			"1669",
			"Schleswig (Stadt)",
			"Mann",
			"Dt. Dichter; Rektor in Heide, Norden und Schleswig"
		],
        [
			"Ratke, Wolfgang",
			"118598481",
			"5",
			"Wolfgang Ratke",
			"wolfgang ratke",
			"",
			"18. Oktober 1571",
			"1571",
			"Wilster",
			"27. April 1635",
			"1635",
			"Erfurt",
			"Mann",
			"Deutscher Theologe, Schriftsteller und Schulreformer"
		],
        [
			"Reimmann, Jacob Friedrich",
			"118599291",
			"5",
			"Jacob Friedrich Reimmann",
			"friedrich remmann",
			"",
			"22. Januar 1668",
			"1668",
			"Gröningen",
			"1. Februar 1743",
			"1743",
			"Hildesheim",
			"Mann",
			"Dt. ev. Theologe und Universalgelehrter; Student in Jena; Rektor in Halberstadt; 1714 Diakon in Magdeburg; ab 1717 Superintendent in Hildesheim"
		],
        [
			"Rettenpacher, Simon",
			"12064536X",
			"5",
			"Simon Rettenpacher",
			"rettenpacher",
			"",
			"1634",
			"1634",
			"",
			"1706",
			"1706",
			"",
			"Mann",
			"Österr. Schriftsteller, Benediktiner i. Stift Kremsmünster, Prof. a.d. Univ. Salzburg, bedeut. Vertreter d. barocken Benediktinerdramas ; Benediktiner, Dichter, Oesterreich"
		],
        [
			"Reuter, Christian",
			"118744690",
			"5",
			"Christian Reuter",
			"christian reuter",
			"",
			"1665",
			"1665",
			"Kütten",
			"1712",
			"1712",
			"",
			"Mann",
			"Deutscher satirischer Dichter; Stud. theol. und jur. in Leipzig; später in Berlin tätig"
		],
        [
			"Riemer, Johannes",
			"118600907",
			"5",
			"Johannes Riemer",
			"johannes riemer",
			"",
			"11. Februar 1648",
			"1648",
			"Halle (Saale)",
			"9. September 1714",
			"1714",
			"Hamburg",
			"Mann",
			"Dt. Theologe und Dichter; Studium und akadem. Laufbahn in Jena; Prof. für Eloquenz und Poesie in Weißenfels; seit 1687 Pastor in Osterwieck bei Halberstadt; seit 1691 Superintendent in Hildesheim; seit 1704 Pastor in Hamburg"
		],
        [
			"Rinckart, Martin",
			"119365324",
			"5",
			"Martin Rinckart",
			"martin rinckart",
			"",
			"24. April 1586",
			"1586",
			"Eilenburg",
			"8. Dezember 1649",
			"1649",
			"Eilenburg",
			"Mann",
			"Dt. ev. Theologe; Pastor, Dichter und Kirchenmusiker"
		],
        [
			"Rist, Johann",
			"118745425",
			"5",
			"Johann Rist",
			"johann rist",
			"",
			"8. März 1607",
			"1607",
			"Ottensen",
			"31. August 1667",
			"1667",
			"Wedel (Holstein)",
			"Mann",
			"Evangelischer Theologe und Poet; Pfarrer in Wedel (Grafschaft Schaumburg) bei Pinneberg; Gründer des Elbschwanenordens"
		],
        [
			"Ritzsch, Gregor",
			"11549801X",
			"5",
			"Gregorius Ritzsch",
			"gregorius ritzsch",
			"",
			"1584",
			"1584",
			"Skytal",
			"15. April 1643",
			"1643",
			"Leipzig",
			"Mann",
			""
		],
        [
			"Roberthin, Robert",
			"12836677X",
			"5",
			"Robert Roberthin",
			"robert roberthin",
			"",
			"3. März 1600",
			"1600",
			"Saalfeld",
			"7. April 1648",
			"1648",
			"Königsberg",
			"Mann",
			"Sekretär des Preuss. Hofgerichts; Dichter; Begründer des Königsberger Dichterkreises (1636-1648) und Freund von Simon Dach; Ehemann von Ursula Roberthin geb. Vogt ; Geistiger Förderer d. Kreises um Simon Dach"
		],
        [
			"Rollenhagen, Gabriel",
			"118791028",
			"5",
			"Gabriel Rollenhagen",
			"rollenhagen",
			"",
			"1583",
			"1583",
			"Magdeburg",
			"1619",
			"1619",
			"",
			"Mann",
			""
		],
        [
			"Rollenhagen, Georg",
			"118749544",
			"5",
			"Georg Rollenhagen",
			"rollenhagen",
			"",
			"22. April 1542",
			"1542",
			"Bernau bei Berlin",
			"20. Mai 1609",
			"1609",
			"Magdeburg",
			"Mann",
			"Deutscher Schriftsteller, Dramatiker, Pädagoge und Prediger"
		],
        [
			"Rompler von Löwenthal, Jesaias",
			"118791109",
			"5",
			"Jesaias Rompler von Löwenhalt",
			"rompler von löwenthal",
			"",
			"1605",
			"1605",
			"",
			"1676",
			"1676",
			"",
			"Mann",
			"Dt. Dichter und Zeichner"
		],
        [
			"Rost, Johann Leonhard",
			"107712423",
			"5",
			"Johann Leonhard Rost",
			"leonhard rost",
			"",
			"14. Februar 1688",
			"1688",
			"Nürnberg",
			"22. März 1727",
			"1727",
			"Nürnberg",
			"Mann",
			"Dt. Mathematiker, Astronom und Dichter"
		],
        [
			"Sacer, Gottfried Wilhelm",
			"119037696",
			"5",
			"Gottfried Wilhelm Sacer",
			"wilhelm sacer",
			"",
			"11. Juli 1635",
			"1635",
			"Naumburg (Saale)",
			"8. September 1699",
			"1699",
			"Wolfenbüttel",
			"Mann",
			"Dt. Satiriker, Übersetzer, Lyriker u. Jurist; Student in Jena (Mag.) und Kiel (Dr.); Advokat in Braunschweig"
		],
        [
			"Scheffler, Johannes",
			"1037614151",
			"5",
			"Johannes Scheffler",
			"johannes scheffler",
			"",
			"25. Dezember 1624",
			"1624",
			"Breslau",
			"9. Juli 1677",
			"1677",
			"Breslau",
			"Mann",
			""
		],
        [
			"Schein, Johann Hermann",
			"118754408",
			"5",
			"Johann Hermann Schein",
			"hermann schein",
			"",
			"20. Januar 1586",
			"1586",
			"Grünhain",
			"19. November 1630",
			"1630",
			"Leipzig",
			"Mann",
			"Dt. Komponist; Musikausbildung in Dresden, Studium in Pforta und Leipzig; Praeceptor bei Gottfried von Wolffersdorf in Weißenfels, 1615 Kapellmeister bei Herzog Johann Ernst d.J. in Weimar, ab 1616 Thomaskantor in Leipzig"
		],
        [
			"Scherffer von Scherffenstein, Wenzel",
			"118607243",
			"5",
			"Wenzel Scherffer",
			"wenzel scherffer",
			"",
			"1603",
			"1603",
			"",
			"1674",
			"1674",
			"",
			"Mann",
			"Dt. Dichter, Übersetzer ; Uebersetzer, Erzieher, Organist, Deutschland"
		],
        [
			"Schirmer, David",
			"118607820",
			"5",
			"David Schirmer",
			"david schirmer",
			"",
			"1623",
			"1623",
			"Pappendorf",
			"1686",
			"1686",
			"Dresden",
			"Mann",
			"Dt. Barockdichter; Hofdichter in Dresden; kursächs. Hofbibliothekar; Mitglied der Deutschgesinnten Genossenschaft"
		],
        [
			"Schirmer, Michael",
			"11727609X",
			"5",
			"Michael Schirmer",
			"michael schirmer",
			"",
			"17. Juli 1606",
			"1606",
			"Leipzig",
			"8. Mai 1673",
			"1673",
			"Berlin",
			"Mann",
			"Dt. ev. Theologe, Pädagoge und Liederdichter; Student in Leipzig, 1630 Magister; 1636 Subrektor und 1651-1668 Konrektor am Grauen Kloster in Berlin; Poeta laureatus"
		],
        [
			"Schmolck, Benjamin",
			"118759965",
			"5",
			"Benjamin Schmolck",
			"benjamin schmolck",
			"",
			"21. Dezember 1672",
			"1672",
			"Brauchitschdorf (Chróstnik)",
			"12. Februar 1737",
			"1737",
			"Schweidnitz",
			"Mann",
			"Past. Prim. und Inspect. der evangelischen Kirchen und Schulen vor Schweidnitz"
		],
        [
			"Schnabel, Johann Gottfried",
			"118609475",
			"5",
			"Johann Gottfried Schnabel",
			"gottfried schnabel",
			"",
			"1692",
			"1692",
			"",
			"1750",
			"1750",
			"",
			"Mann",
			""
		],
        [
			"Schneuber, Johann Matthias",
			"100268579",
			"5",
			"Johann Matthias Schneuber",
			"matthias schneuber",
			"",
			"1614",
			"1614",
			"",
			"1665",
			"1665",
			"",
			"Mann",
			"Straßburg (Wirkungsort); Mitglied der Fruchtbringenden Gesellschaft; Elsässischer Dichter und Astronom; Gymnasialdirektor"
		],
        [
			"Schoch, Johann Georg",
			"118064665",
			"5",
			"Johann Georg Schoch",
			"georg schoch",
			"",
			"1634",
			"1634",
			"",
			"1688",
			"1688",
			"",
			"Mann",
			"Dt. Dichter"
		],
        [
			"Schoppe, Caspar",
			"119298600",
			"5",
			"Caspar Schoppe",
			"caspar schoppe",
			"",
			"27. Mai 1576",
			"1576",
			"Neumarkt i.d. OPf.",
			"19. November 1649",
			"1649",
			"Padua",
			"Mann",
			"Studium der Jurisprudenz in Heidelberg, Altdorf u. Ingolstadt, wurde 1598 katholisch; Graf von Clara-Valle; benutzte zahlreiche Pseudonyme"
		],
        [
			"Schorer, Christoph",
			"100264913",
			"5",
			"Christoph Schorer",
			"christoph schorer",
			"",
			"1618",
			"1618",
			"",
			"1671",
			"1671",
			"",
			"Mann",
			""
		],
        [
			"Schott, Caspar",
			"121882128",
			"5",
			"Kaspar Schott",
			"kaspar schott",
			"",
			"5. Februar 1608",
			"1608",
			"Bad Königshofen i. Grabfeld",
			"22. Mai 1666",
			"1666",
			"Würzburg",
			"Mann",
			"Dt. Mathematiker, Physiker und Polyhistor; 1627 Eintritt in die Gesellschaft Jesu; Studium der Philosophie in Würzburg; 1631 nach dem Einmarsch der Schweden Flucht nach Italien; Abschluss des Studiums der Theologie, Philosophie und Mathematik in Palermo, dort Prof. der Mathematik und Moraltheologie; 1652-1655 Mitarbeiter von Athanasius Kircher in Rom; lehrte danach in Mainz und schließlich als Prof. der Mathematik und Physik in Würzburg ; Jesuit"
		],
        [
			"Schottelius, Justus Georg",
			"118610554",
			"5",
			"Justus Georg Schottel",
			"georg schottel",
			"",
			"23. Juni 1612",
			"1612",
			"Einbeck",
			"25. Oktober 1676",
			"1676",
			"Wolfenbüttel",
			"Mann",
			"Prinzenerzieher am Wolfenbütteler Hof"
		],
        [
			"Schupp, Johann Balthasar",
			"118762672",
			"5",
			"Johann Balthasar Schupp",
			"balthasar schupp",
			"",
			"1. März 1610",
			"1610",
			"Gießen",
			"26. Oktober 1661",
			"1661",
			"Hamburg",
			"Mann",
			"Präpositus zu Hamburg; lutherischer Theologe; Professor der Rhetorik; Historiker ; Dt. ev. Theologe u. Moralsatiriker, 1625 in Marburg immatrikuliert, 1631 Magister in Rostock, 1635 Prof. in Marburg, 1643 auch Pfarrer an der Elisabethkirche, 1645 Dr. theol., 1646 Hofprediger und Konsistorialrat des Landgrafen von Hessen in Braubach, seit 1649 Hauptpfarrer an der Jacobikirche in Hamburg"
		],
        [
			"Schwarz, Sibylle",
			"118762974",
			"5",
			"Sibylle Schwarz",
			"sibylle schwarz",
			"",
			"14. Februar 1621",
			"1621",
			"Greifswald",
			"31. Juli 1638",
			"1638",
			"Greifswald",
			"Frau",
			"Dt. Dichterin; Tochter von Christian Schwarz, fürstlich pommerscher Landrat und Bürgermeister in Greifswald, und Regina Völschow (1582-1630)"
		],
        [
			"Schwieger, Jacob",
			"118795791",
			"5",
			"Jakob Schwieger",
			"jakob schwieger",
			"",
			"1630",
			"1630",
			"",
			"1661",
			"1661",
			"",
			"Mann",
			"Dichter"
		],
        [
			"Simler, Johann Wilhelm",
			"119151693",
			"5",
			"Johann Wilhelm Simler",
			"wilhelm simler",
			"",
			"29. August 1605",
			"1605",
			"Zürich",
			"14. März 1672",
			"1672",
			"Zürich",
			"Mann",
			"Schweizer reformierter Theologe und Dichter; Promotion 1627 in Genf; 1629 Pfarrer in Uetikon, 1631 in Herrliberg; 1632 Kurator der Zürcher Bürgerbibliothek, 1638 Lehrer und Inspektor am Collegium zum Fraumünster"
		],
        [
			"Spangenberg, Wolfhart",
			"119066947",
			"5",
			"Wolfhart Spangenberg",
			"hart spangenberg",
			"",
			"1567",
			"1567",
			"Mansfeld",
			"1636",
			"1636",
			"",
			"Mann",
			"Dt. Meistersänger und Dichter, Übersetzer und Prediger; Mitglied der Straßburger Gesellschaft der Meistersinger"
		],
        [
			"Spee, Friedrich von",
			"11861598X",
			"5",
			"Friedrich von Spee",
			"friedrich von spee",
			"",
			"25. Februar 1591",
			"1591",
			"Kaiserswerth",
			"7. August 1635",
			"1635",
			"Trier",
			"Mann",
			""
		],
        [
			"Speer, Daniel",
			"118616005",
			"6",
			"Daniel Speer",
			"daniel speer",
			"",
			"2. Juli 1636",
			"1636",
			"Breslau",
			"5. Oktober 1707",
			"1707",
			"Göppingen",
			"Mann",
			"aus Breslau; wirkte überwiegend in Göttingen und Stuttgart; Komponist, Musiktheoretiker, Romanautor und Pädagoge ; Komponist, Pädagoge"
		],
        [
			"Stieler, Kaspar",
			"118618121",
			"6",
			"Kaspar von Stieler",
			"von stieler",
			"",
			"2. August 1632",
			"1632",
			"Erfurt",
			"24. Juni 1707",
			"1707",
			"Erfurt",
			"Mann",
			"Dt. Dichter, Gelehrter und Sprachwissenschaftler; ab 1668 Mitglied der Fruchtbringenden Gesellschaft («der Spate»); 1705 geadelt"
		],
        [
			"Stökken, Christian von",
			"129584673",
			"6",
			"Christian von Stökken",
			"von stökken",
			"",
			"15. August 1633",
			"1633",
			"Rendsburg",
			"4. September 1684",
			"1684",
			"Rendsburg",
			"Mann",
			"Dt. ev. Theologe und Poet; 1656 Pastor in Trittau; 1664 Hofprediger und Superintendent in Eutin; ab 1678 Generalsuperintendent in Rendsburg; ab 1675 Mitglied der Deutschgesinnten Genossenschaft (Der Andächtige)"
		],
        [
			"Stubenberg, Johann Wilhelm von",
			"118756141",
			"6",
			"Johann Wilhelm von Stubenberg",
			"von stubenberg",
			"",
			"22. April 1619",
			"1619",
			"Nové Město nad Metují",
			"15. März 1663",
			"1663",
			"Wien",
			"Mann",
			"Dt. Dichter; Mitglied der Fruchtbringenden Gesellschaft (Der Unglückselige)"
		],
        [
			"Taubmann, Friedrich",
			"117247243",
			"6",
			"Friedrich Taubmann",
			"friedrich taubmann",
			"",
			"16. Mai 1565",
			"1565",
			"Wonsees",
			"24. März 1613",
			"1613",
			"Wittenberg",
			"Mann",
			"Dt. Historiker, Philologe und Dichter; Professor der Poesie und Dekan der Phil. Fakultät Wittenberg; Poeta laureatus ; Humanist"
		],
        [
			"Titz, Johann Peter",
			"104333278",
			"6",
			"Johann Peter Titz",
			"peter titz",
			"",
			"10. Januar 1617",
			"1617",
			"Liegnitz",
			"7. September 1689",
			"1689",
			"Danzig",
			"Mann",
			"Dt. Philologe und Liederdichter; Prof. der Rhetorik und Poesie in Danzig"
		],
        [
			"Treuer, Gotthilf",
			"104367318",
			"6",
			"Gotthilf Treuer",
			"gotthilf treuer",
			"",
			"11. Februar 1632",
			"1632",
			"Beeskow",
			"20. März 1711",
			"1711",
			"Frankfurt (Oder)",
			"Mann",
			"Dt. ev. Theologe und Pädagoge; Student in Altdorf, Wittenberg (?) und Frankfurt/O.; ab 1652 Subrektor am Berlinischen Gymnasium; 1660 Diakon in Beeskow; 1672 Diakon an St. Nicolai Frankfurt/O. ; 1674 Diakon an St. Marien Frankfurt/O., 1676 Archidiakon"
		],
        [
			"Trömer, Johann Christian",
			"123834252",
			"6",
			"Johann Christian Trömer",
			"christian trömer",
			"",
			"XX.XX.1697",
			"1697",
			"Dresden",
			"1. Mai 1756",
			"1756",
			"Dresden",
			"Mann",
			"Dresdner Buchhändler und Schriftsteller ; Schriftsteller, Buchhändler"
		],
        [
			"Tscherning, Andreas",
			"118802879",
			"6",
			"Andreas Tscherning",
			"tscherning",
			"",
			"18. November 1611",
			"1611",
			"Bunzlau",
			"27. September 1659",
			"1659",
			"Rostock",
			"Mann",
			"Dt. Dichter, Schriftsteller; Hochschullehrer; studierte Orientalistik; Hauslehrer in Breslau, ab 1644 Prof. der Dichtkunst an der Univ. Rostock"
		],
        [
			"Vetter, Conrad",
			"11739646X",
			"6",
			"Conrad Vetter",
			"conrad vetter",
			"",
			"1546",
			"1546",
			"Engen",
			"11. Oktober 1622",
			"1622",
			"München",
			"Mann",
			"Dt. Jesuit (SJ) und kathol. Kontroverstheologe; Domprediger in Regensburg (1588-1607)"
		],
        [
			"Weckherlin, Georg Rudolph",
			"118629840",
			"6",
			"Georg Rodolf Weckherlin",
			"weckherlin",
			"",
			"1584",
			"1584",
			"",
			"1653",
			"1653",
			"",
			"Mann",
			"Dt. Schriftsteller ; Schriftsteller"
		],
        [
			"Weise, Christian",
			"118630369",
			"6",
			"Christian Weise",
			"christian weise",
			"",
			"29. April 1642",
			"1642",
			"Zittau",
			"21. Oktober 1708",
			"1708",
			"Zittau",
			"Mann",
			"Dt. Pädagoge, Dichter, Rhetoriker; Student in Leipzig, 1663 Magister; Lehrer in Weißenfels; ab 1678 Rektor am Gymnasium Zittau und Leiter der Ratsbibliothek Zittau"
		],
        [
			"Werder, Diederich von dem",
			"118767038",
			"6",
			"Diederich von dem Werder",
			"von dem werder",
			"",
			"17. Januar 1584",
			"1584",
			"Werdershausen",
			"18. Dezember 1657",
			"1657",
			"Reinsdorf",
			"Mann",
			"Dichter, Diplomat, Übersetzer, schwedischer Obrist, kurbrandenburgischer Obrist, Kriegsrat, Amtshauptmann von Alt-Gatersleben; Mitglied der Fruchtbringenden Gesellschaft (Der Vielgekörnte)"
		],
        [
			"Wernicke, Christian",
			"118631586",
			"6",
			"Christian Wernicke",
			"christian wernicke",
			"",
			"1661",
			"1661",
			"Elbing",
			"1725",
			"1725",
			"Kopenhagen",
			"Mann",
			"Dt. Jurist, Diplomat u. Dichter (Epigrammatiker); Studium der Rechts- und Staatswissenschaften in Kiel; ab 1709 dänischer Kanzleirat am französischen Königshof; ab 1724 lebte er in Kopenhagen ; Diplomat, Schriftsteller"
		],
        [
			"Zesen, Philipp von",
			"118636596",
			"6",
			"Philipp von Zesen",
			"von zesen",
			"",
			"8. Oktober 1619",
			"1619",
			"Priorau",
			"13. November 1689",
			"1689",
			"Hamburg",
			"Mann",
			"Deutscher Romanautor, Lyriker, Sprachtheoretiker und Übersetzer; Gründer der Deutschgesinnten Genossenschaft (Der Färtige); Mitglied der Fruchtbringenden Gesellschaft (Der Wohlsetzende); 1653 vom Kaiser geadelt"
		],
        [
			"Zigler und Kliphausen, Heinrich Anshelm von",
			"118772902",
			"6",
			"Heinrich Anselm von Ziegler und Kliphausen",
			"kliphausen",
			"",
			"6. Januar 1663",
			"1663",
			"Radomierzyce",
			"8. September 1697",
			"1697",
			"Liebertwolkwitz",
			"Mann",
			"Dt. Dichter und Geschichtsschreiber; Herr von und auff Klipphauß, Radmeritz, Probsthain und Linda; Ehemann von Dorothea Sabina von Ziegler und Kliphausen geb. von Lindenau (Tochter des kursächs. Oberküchenmeisters Wolf von Lindenau auf Machern) ; Schriftsteller"
		],
        [
			"Zimmermann, Johann Jacob",
			"118127055",
			"6",
			"Johann Jakob Zimmermann",
			"jakob zimmermann",
			"",
			"1644",
			"1644",
			"Vaihingen an der Enz",
			"1693",
			"1693",
			"Rotterdam",
			"Mann",
			"Theologe, Astrologe, Studium der Theologie in Tübingen, 1664 Magister, 1671 Pfarrer in Bietigheim, 1685 als religiöser Schwärmer seines Amtes enthoben, Anhänger Jakob Böhmes ; Theologe, Mathematiker, Astrologe ; Anhänger Böhmes* Nicht identisch mit Zimmermann, Johannes Jakob. geb. 1695,  u. Zimmermann, Johann Jacob , Respondenten aus Tübingen u. Straßburg"
		],
        [
			"Zincgref, Julius Wilhelm",
			"11885870X",
			"6",
			"Julius Wilhelm Zincgref",
			"wilhelm zincgref",
			"",
			"3. Juni 1591",
			"1591",
			"Heidelberg",
			"12. November 1635",
			"1635",
			"St. Goar",
			"Mann",
			"Dt. frühbarocker Lyriker und Epigrammatiker des Heidelberger Kreises"
        ]
    ]

class Person:
    def __init__(self, row):
        self.name = row[0]
        self.gnd = row[1]
        self.vol = row[2]
        self.nameGND = row[3]
        self.query = row[4]
        self.regex = row[5]
        self.dateBirth = row[6]
        self.yearBirth = row[7]
        self.placeBirth = row[8]
        self.dateDeath = row[9]
        self.yearDeath = row[10]
        self.placeDeath = row[11]
        self.gender = row[12]
        self.bio = row[13]
    def __str__(self):
        ret = self.name
        if self.yearBirth and self.yearDeath:
            ret = ret + f" ({self.yearBirth}–{self.yearDeath})"        
        if self.gnd:
            ret = ret + ", GND " + self.gnd
        return(ret)
        
def get_persons():
    return([Person(row) for row in PersonList.content])
    
def get_query_words():
    return([row[4] for row in PersonList.content])

def get_gnds():
    persons = get_persons()
    return([pers.gnd for pers in persons])

def test_gnd(gnd):
    gnds = get_gnds()
    if gnd in gnds:
        return(True)
    return(False)