#!/usr/bin/python3
# -*- coding: utf-8 -*-

class Code:
	# Quelle: https://www.loc.gov/standards/iso639-2/php/code_list.php
	conc = {
		"amh" : "Amharisch",
		"ang" : "Altenglisch",
		"ara" : "Arabisch",
		"arc" : "Aramäisch",
		"arg" : "Aragonisch",
		"arm" : "Armenisch",
		"ast" : "Asturisch",
		"ave" : "Avestisch",
		"aze" : "Aserbaidschanisch",
		"baq" : "Baskisch",
		"bel" : "Weißrussisch",
		"bre" : "Bretonisch",
		"bul" : "Bulgarisch",
		"cat" : "Katalanisch",
		"chi" : "Chinesisch",
		"chu" : "Kirchenslawisch",
		"cop" : "Koptisch",
		"cos" : "Korsisch",
		"csb" : "Kaschubisch",
		"cze" : "Tschechisch",
		"dan" : "Dänisch",
		"dar" : "Dari",
		"dsb" : "Niedersorbisch",
		"dum" : "Mittelniederländisch",
		"dut" : "Niederländisch",
		"eng" : "Englisch",
		"enm" : "Mittelenglisch",
		"epo" : "Esperanto",
		"est" : "Estnisch",
		"fin" : "Finnisch",
		"fre" : "Französisch",
		"frm" : "Mittelfranzösisch",
		"fro" : "Altfranzösisch",
		"fry" : "Friesisch",
		"fur" : "Friulisch",
		"geo" : "Georgisch",
		"ger" : "Deutsch",
		"gez" : "Altäthiopisch",
		"gla" : "Gälisch-Schottisch",
		"gle" : "Irisch",
		"glg" : "Galicisch",
		"gmh" : "Mittelhochdeutsch",
		"goh" : "Althochdeutsch",
		"got" : "Gotisch",
		"grc" : "Altgriechisch",
		"gre" : "Neugriechisch",
		"gsw" : "Waliserdeutsch",
		"heb" : "Hebräisch",
		"hin" : "Hindu",
		"hit" : "Hethitisch",
		"hrv" : "Kroatisch",
		"hsb" : "Hochsorbisch",
		"hun" : "Ungarisch",
		"ice" : "Isländisch",
		"ind" : "Indonesisch",
		"ita" : "Italienisch",
		"jpn" : "Japanisch",
		"kal" : "Grönländisch",
		"kor" : "Koreanisch",
		"kur" : "Kurdisch",
		"lad" : "Judeo-Español",
		"lat" : "Latein",
		"lav" : "Lettisch",
		"lit" : "Litauisch",
		"ltz" : "Luxemburgisch",
		"mac" : "Makedonisch",
		"may" : "Malaiisch",
		"mga" : "Mittelirisch",
		"mis" : "Verschiedene Sprachen",
		"mlt" : "Maltesisch",
		"mnc" : "Manchu",
		"mol" : "Moldauisch",
		"mon" : "Mongolisch",
		"mul" : "Verschiedene Sprachen",
		"nap" : "Neapolitanisch",
		"nds" : "Niederdeutsch",
		"non" : "Altnordisch",
		"nor" : "Norwegisch",
		"oci" : "Okzitanisch",
		"ota" : "Osmanisch",
		"pal" : "Mittelpersisch",
		"peo" : "Altpersisch",
		"per" : "Persisch",
		"phn" : "Phönikisch",
		"pol" : "Polnisch",
		"por" : "Portugiesisch",
		"pro" : "Altprovenzalisch",
		"pus" : "Paschtu",
		"qhe" : "Althebräisch",
		"roh" : "Rätoromanisch",
		"rom" : "Romani",
		"rum" : "Rumänisch",
		"rus" : "Russisch",
		"sam" : "Samaritanisch",
		"san" : "Sanskrit",
		"sco" : "Schottisch",
		"sga" : "Altirisch",
		"sla" : "Slawische Sprachen",
		"slo" : "Slowakisch",
		"slv" : "Slovenisch",
		"som" : "Somali",
		"spa" : "Spanisch",
		"srd" : "Sardisch",
		"srp" : "Serbisch",
		"sux" : "Sumerisch",
		"swa" : "Suaheli",
		"swe" : "Schwedisch",
		"syr" : "Syrisch",
		"tat" : "Tatarisch",
		"tha" : "Thailändisch",
		"tib" : "Tibetisch",
		"tuk" : "Turkmenisch",
		"tup" : "Tupi-Sprache",
		"tur" : "Türkisch",
		"ukr" : "Ukrainisch",
		"und" : "Unbestimmbare Sprache",
		"uzb" : "Usbekisch",
		"vie" : "Vietnamesisch",
		"vol" : "Volapük",
		"wel" : "Walisisch",
		"wen" : "Sorbisch",
		"yid" : "Jiddisch"
		}
def getLang(code):
	try:
		return(Code.conc[code])
	except:
		return(False)
def getCode(language):
	for key in Code.conc:
		try:
			return(Code.conc[key])
		except:
			pass
	return(False)